# https://github.com/goreleaser/goreleaser-action
name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  create:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-go@v5
        with:
          go-version: ^1.19.4
          check-latest: true

      - name: release
        if: startsWith(github.event.ref, 'refs/tags')
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: myfolder/dist/*
