# https://github.com/goreleaser/goreleaser-action
name: release

on:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    # "released" events are emitted either when directly be released or be edited from pre-released.
    types: [prereleased, released]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-go@v5
        with:
          go-version: ^1.19.4
          check-latest: true

      - name: release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: release-assets-${{ github.sha }}
          path: dist/*
          retention-days: 1

  deploy:
    needs: goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-assets-${{ github.sha }}
          merge-multiple: true
          path: dist/*

      - name: List
        run: find ./dist

      - name: Release
        if: github.event_name == 'release' && !github.event.release.prerelease
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*
